window.VENUS_SITE = {
  businessName: "Venus Club & Banquet Hall",
  shortName: "Venus Club",
  tagline: "One Destination for Every Celebration.",
  area: "Barabanki near Lucknow, Uttar Pradesh",
  phoneDisplay: "+91 9664345780",
  phoneHref: "tel:+919664345780",
  whatsappHref:
    "https://wa.me/919664345780?text=Hello%2C%20I%20would%20like%20to%20plan%20an%20event%20at%20Venus%20Club%20%26%20Banquet%20Hall.",
  whatsappLabel: "WhatsApp Us",
  addressLine1: "Full venue address to be updated",
  addressLine2: "Barabanki, Uttar Pradesh",
  mapsHref:
    "https://www.google.com/maps/search/?api=1&query=Venus+Club+Barabanki",
  email: "bookings@venusbbk.com",
  guestCapacity: "Capacity details available on enquiry",
  roomCount: "10 guest rooms",
  heroBlurb:
    "An elegant destination in Barabanki for weddings, celebrations, corporate gatherings, and memorable stays.",
  metaDescription:
    "Venus Club & Banquet Hall is a premium event venue in Barabanki near Lucknow with a banquet hall, outdoor celebration space, guest accommodation, and enquiry-first planning.",
  launchBannerText: "Launching on July 29, 2026",
  canonicalBase: "https://venusbbk.com",
  inquiryEndpoint:
    "https://script.google.com/macros/s/AKfycbyk7WsEajmK8mro2jc866nGdELNdnj3Mc1gRtnJs_iujGxtAPbK5tDbsWujiz0Df351oQ/exec",
  inquiryMethod: "POST",
  inquiryMode: "no-cors",
  launchAnnouncement: {
    enabled: true,
    date: "2026-07-29",
    title: "Venus Club\nOpening Summer 2026",
    message:
      "A new destination for extraordinary weddings, celebrations and private stays.\n\nWe are carefully preparing every detail and are now welcoming early enquiries and private venue appointments.",
    primaryLabel: "Plan Your Event",
    primaryHref: "contact.html#schedule-visit",
    secondaryLabel: "Continue to Website",
    image: "venue-hall.jpeg",
    imageAlt: "Interior ambience at Venus Club",
    monogram: "VC",
    openingLabel: "Opening 29 July 2026",
  },
  galleryItems: [
    {
      title: "Banquet Hall Perspective",
      category: "banquet",
      image: "venue-hall.jpeg",
      alt: "Banquet hall at Venus Club with warm lighting and stage-facing perspective",
      caption: "The indoor hall anchors ceremonies, receptions, and formal hosted gatherings.",
    },
    {
      title: "Hall Atmosphere",
      category: "banquet",
      image: "venue-hall.jpeg",
      alt: "Interior view of the main hall showing event-ready ambience at Venus Club",
      caption: "A calm interior character suited to celebrations that need scale and composure.",
    },
    {
      title: "Outdoor Evening Mood",
      category: "outdoor",
      image: "outdoor_lawn.png",
      alt: "Outdoor celebration area at Venus Club with evening lighting ambience",
      caption: "The lawn setting introduces a softer, more open-air experience for evenings.",
    },
    {
      title: "Garden Arrival Impression",
      category: "outdoor",
      image: "venue-garden.jpeg",
      alt: "Garden-side visual atmosphere at Venus Club for receptions and gatherings",
      caption: "Ideal for arrival moments, outdoor receptions, and more atmospheric event styling.",
    },
    {
      title: "Celebration Character",
      category: "social",
      image: "venue-hall.jpeg",
      alt: "Venue ambience inside Venus Club suitable for weddings and family celebrations",
      caption: "A setting designed to adapt across weddings, birthdays, anniversaries, and family functions.",
    },
    {
      title: "Venue Ambience",
      category: "details",
      image: "venue-garden.jpeg",
      alt: "Exterior ambience at Venus Club near Barabanki for event hosting",
      caption: "Current venue imagery will expand as more professionally shot albums are added.",
    },
  ],
};
