window.VENUS_SITE = {
  businessName: "Venus Club & Banquet Hall",
  shortName: "Venus Club",
  tagline: "One Destination for Every Celebration.",
  area: "Barabanki, Lucknow, Uttar Pradesh",
  businessHoursDisplay: "9:00 AM to 9:00 PM",
  phoneDisplay: "+91 9664345780",
  phoneHref: "tel:+919664345780",
  whatsappHref:
    "https://wa.me/919664345780?text=Hello%2C%20I%20would%20like%20to%20plan%20an%20event%20at%20Venus%20Club%20%26%20Banquet%20Hall.",
  whatsappLabel: "WhatsApp Us",
  instagramHref: "https://www.instagram.com/venusbbk",
  addressLine1: "Lucknow - Colonelganj - Gonda Rd, Dharsania, Gadia",
  addressLine2: "Uttar Pradesh 225003, India",
  mapsHref:
    "https://www.google.com/maps/place/Venus+Club+and+Banquet/data=!4m2!3m1!1s0x0:0x545008718fb33479?sa=X&ved=1t:2428&ictx=111",
  email: "bookings@venusbbk.com",
  guestCapacity: "Up to 1000 guests",
  roomCount: "10 guest rooms",
  serviceAreas: [
    "Lucknow",
    "Barabanki",
    "Dharsania",
    "Gadia",
    "Banki",
    "Safedabad",
    "Chinhat",
    "Dewa",
    "Zaidpur",
    "Nawabganj",
    "Aseni",
    "Madhopur"
  ],
  seoKeywords:
    "Venus Club, Venus Banquet, Venus Outdoor Lawn, Club, Outdoor, Event, Business Event, Venue, Marriage Hall, Banquet Hall, Wedding Venue, Outdoor Lawn, Corporate Event Venue, Barabanki, Lucknow",
  heroBlurb:
    "A refined venue in Barabanki for weddings, celebrations, corporate gatherings, and guest stays.",
  metaDescription:
    "Venus Club & Banquet Hall is a premium event venue in Barabanki near Lucknow with a banquet hall, outdoor celebration space, guest accommodation, and enquiry-first planning.",
  launchBannerText: "Launching on July 30, 2026",
  venueFacts: [
    {
      title: "Up to 1000 guests",
      detail: "Suitable for weddings, receptions, and larger hosted gatherings",
    },
    {
      title: "Banquet hall and outdoor lawn",
      detail: "Indoor and open-air hosting in one destination",
    },
    {
      title: "10 guest rooms",
      detail: "Useful for wedding families and travelling guests",
    },
    {
      title: "Barabanki and Lucknow access",
      detail: "Convenient for local events and nearby city guests",
    },
  ],
  eventTypes: [
    "Wedding",
    "Reception",
    "Engagement",
    "Birthday",
    "Anniversary",
    "Family Function",
    "Corporate Event",
    "Conference / Seminar",
    "Private Gathering",
  ],
  canonicalBase: "https://venusbbk.com",
  inquiryEndpoint:
    "https://script.google.com/macros/s/AKfycbyk7WsEajmK8mro2jc866nGdELNdnj3Mc1gRtnJs_iujGxtAPbK5tDbsWujiz0Df351oQ/exec",
  inquiryMethod: "POST",
  inquiryMode: "no-cors",
  launchAnnouncement: {
    enabled: true,
    date: "2026-07-30",
    delayMs: 1800,
    title: "Venus Club\nOpening Summer 2026",
    message:
      "Now welcoming early enquiries for weddings, celebrations, private stays, and venue visits ahead of our opening.",
    primaryLabel: "Check Availability",
    primaryHref: "contact.html#schedule-visit",
    image: "venue-garden.jpeg",
    imageAlt: "Venue ambience at Venus Club",
    monogram: "VC",
    openingLabel: "Opening 30 July 2026",
  },
  galleryItems: [
    {
      title: "Banquet Hall Perspective",
      category: "banquet",
      image: "venue-hall.jpeg",
      alt: "Banquet hall at Venus Club with warm lighting and stage-facing perspective",
      caption: "The indoor hall anchors ceremonies, receptions, and formal hosted gatherings.",
    },
    {
      title: "Hall Atmosphere",
      category: "banquet",
      image: "venue-hall.jpeg",
      alt: "Interior view of the main hall showing event-ready ambience at Venus Club",
      caption: "A calm interior character suited to celebrations that need scale and composure.",
    },
    {
      title: "Outdoor Evening Mood",
      category: "outdoor",
      image: "outdoor_lawn.png",
      alt: "Outdoor celebration area at Venus Club with evening lighting ambience",
      caption: "The lawn setting introduces a softer, more open-air experience for evenings.",
    },
    {
      title: "Garden Arrival Impression",
      category: "outdoor",
      image: "venue-garden.jpeg",
      alt: "Garden-side visual atmosphere at Venus Club for receptions and gatherings",
      caption: "Ideal for arrival moments, outdoor receptions, and more atmospheric event styling.",
    },
    {
      title: "Celebration Character",
      category: "social",
      image: "venue-hall.jpeg",
      alt: "Venue ambience inside Venus Club suitable for weddings and family celebrations",
      caption: "A setting designed to adapt across weddings, birthdays, anniversaries, and family functions.",
    },
    {
      title: "Corporate Event Setting",
      category: "social",
      image: "corporate_event.png",
      alt: "Corporate meeting and hosted event setup at Venus Club",
      caption: "A more formal setup suited to meetings, hosted business events, and professional gatherings.",
    },
    {
      title: "Venue Ambience",
      category: "details",
      image: "venue-garden.jpeg",
      alt: "Exterior ambience at Venus Club near Barabanki for event hosting",
      caption: "Current venue imagery will expand as more professionally shot albums are added.",
    },
  ],
};